name: 5term-main

on:
  push:
    branches: ['feature/docker']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          docker login https://ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GHCR_TOKEN }}
          docker build -t ghcr.io/${{ github.repository_owner }}/nest .
          docker push ghcr.io/${{ github.repository_owner }}/nest

      - name: Clean AWS Credentials
        run: |
          unset AWS_DEFAULT_REGION
          unset AWS_REGION
          unset AWS_ACCESS_KEY_ID
          unset AWS_SECRET_ACCESS_KEY
          unset AWS_SESSION_TOKEN

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: AWS EC2 Connection
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          password: ${{ secrets.EC2_PASSWORD }}
          port: ${{ secrets.EC2_SSH_PORT }}
          timeout: 60s
          script: |
            sudo docker stop nest-container || true  
            sudo docker rm nest-container || true    
            sudo docker pull ghcr.io/${{ github.repository_owner }}/nest:latest
            sudo docker run -it -d -p 3002:3000 --name nest-container ghcr.io/${{ github.repository_owner }}/nest:latest
