name: 5term-main

on:
  push:
    branches: ['feature/docker']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Image Tag
        id: tag
        run: echo "::set-output name=tag::$(date +'%Y%m%d%H%M%S')"

      - name: Build Docker Image
        run: |
          docker login ghcr.io -u ${{ secrets.GHCR_ID }} -p ${{ secrets.GHCR_TOKEN }}
          docker build -t ghcr.io/${{ secrets.GHCR_ID }}/nest:${{ steps.tag.outputs.tag }} .
          docker push ghcr.io/${{ secrets.GHCR_ID }}/nest:${{ steps.tag.outputs.tag }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: AWS EC2 Connection
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          password: ${{ secrets.EC2_PASSWORD }}
          port: ${{ secrets.EC2_SSH_PORT }}
          timeout: 60s
          script: |
            cd usr/src/app
            docker-compose down
            docker-compose pull
            docker-compose up -d
